apiVersion: apps/v1
kind: Deployment
metadata:
  name: tonys-blax
  namespace: tns
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tonys-blax
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tonys-blax
        product: tonys-blax
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "3600"
        name: tonys-blax
